// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type ExecReq struct {
	Database string   `json:"database,default=default"`
	SQL      string   `json:"sql"`
	Args     []string `json:"args,optional"`
}

type ExecResp struct {
	Status Status     `json:"status"`
	Data   ExecResult `json:"data"`
}

type ExecResult struct {
	ID           int64 `json:"id"`
	RowsAffected int64 `json:"rowsAffected"`
}

type RawReq struct {
	Database string   `json:"database,default=default"`
	SQL      string   `json:"sql"`
	Args     []string `json:"args,optional"`
}

type RawResp struct {
	Status Status                   `json:"status"`
	Data   []map[string]interface{} `json:"data"`
}

type Status struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}
