// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type CreateData struct {
	Id int64 `json:"id"`
}

type CreateReq struct {
	Database string          `json:"database"`
	ValPairs []CreateValPair `json:"valPairs"`
}

type CreateResp struct {
	Status Status     `json:"status"`
	Data   CreateData `json:"data"`
}

type CreateValPair struct {
	Col string `json:"col"`
	Val string `json:"val"`
}

type DDLReq struct {
	Sql string `json:"sql"`
}

type DDLResp struct {
	Status Status `json:"status"`
}

type Status struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}
