// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	sqlitev1 "github.com/Ikaros727/sqlite-lab/internal/handler/sqlite/v1"
	"github.com/Ikaros727/sqlite-lab/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				//
				Method:  http.MethodPost,
				Path:    "/ddl",
				Handler: sqlitev1.DDLHandler(serverCtx),
			},
			{
				// 执行 CREATE 方法
				Method:  http.MethodPost,
				Path:    "/dml/create",
				Handler: sqlitev1.CreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/sqlite/v1"),
	)
}
