// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	opensqlv1 "github.com/Ikaros727/sqlite-lab/internal/handler/opensql/v1"
	"github.com/Ikaros727/sqlite-lab/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/exec",
				Handler: opensqlv1.ExecHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/raw",
				Handler: opensqlv1.RawHandler(serverCtx),
			},
		},
		rest.WithPrefix("/opensql/v1"),
	)
}
